// Complete Fort Database with all information
const fortsData = {
    // Rajasthan Forts
    'red fort': {
        name: 'Red Fort',
        location: 'Delhi',
        state: 'Delhi',
        lat: 28.6562,
        lng: 77.2410,
        built: '1638-1648',
        builtBy: 'Emperor Shah Jahan',
        architecture: 'Mughal Architecture',
        unesco: 'Yes (2007)',
        constructionCost: 'Estimated 10 million rupees (17th century)',
        timePeriod: '10 years',
        description: 'The Red Fort is a historic fortification in Old Delhi that served as the main residence of the Mughal emperors for nearly 200 years.',
        significance: 'Symbol of Indian independence, hosts the Prime Minister\'s Independence Day speech annually',
        visitingHours: '9:30 AM - 4:30 PM (Closed on Mondays)',
        entryFee: '₹35 for Indians, ₹500 for Foreigners',
        bestTime: 'October to March',
        nearbyAttractions: 'Jama Masjid, Chandni Chowk, Raj Ghat',
        icon: '🏰'
    },
    'amber fort': {
        name: 'Amber Fort',
        location: 'Jaipur, Rajasthan',
        state: 'Rajasthan',
        lat: 26.9855,
        lng: 75.8513,
        built: '1592',
        builtBy: 'Raja Man Singh I',
        architecture: 'Rajput and Mughal Architecture',
        unesco: 'Yes (2013)',
        constructionCost: 'Not documented, built over several generations',
        timePeriod: 'Over 150 years',
        description: 'Amber Fort is known for its artistic Hindu style elements and grand scale. Located high on a hill, it overlooks Maota Lake.',
        significance: 'One of the most important forts of Rajasthan, showcases the grandeur of Rajput rulers',
        visitingHours: '8:00 AM - 6:00 PM (Daily)',
        entryFee: '₹100 for Indians, ₹500 for Foreigners',
        bestTime: 'October to March',
        nearbyAttractions: 'Jaigarh Fort, Nahargarh Fort, City Palace, Hawa Mahal',
        icon: '⚔️'
    },
    'mehrangarh fort': {
        name: 'Mehrangarh Fort',
        location: 'Jodhpur, Rajasthan',
        state: 'Rajasthan',
        lat: 26.2984,
        lng: 73.0189,
        built: '1459',
        builtBy: 'Rao Jodha',
        architecture: 'Rajput Architecture',
        unesco: 'No',
        constructionCost: 'Built over centuries, exact cost unknown',
        timePeriod: 'Construction continued for 500+ years',
        description: 'One of the largest forts in India, standing 400 feet above Jodhpur.',
        significance: 'Symbol of Marwar kingdom power',
        visitingHours: '9:00 AM - 5:00 PM (Daily)',
        entryFee: '₹100 for Indians, ₹600 for Foreigners',
        bestTime: 'October to March',
        nearbyAttractions: 'Jaswant Thada, Umaid Bhawan Palace',
        icon: '🛡️'
    },
    'jaisalmer fort': {
        name: 'Jaisalmer Fort',
        location: 'Jaisalmer, Rajasthan',
        state: 'Rajasthan',
        lat: 26.9124,
        lng: 70.9166,
        built: '1156',
        builtBy: 'Rawal Jaisal',
        architecture: 'Rajput Architecture',
        unesco: 'Yes (2013)',
        constructionCost: 'Not precisely documented',
        timePeriod: 'Initial 10 years, expanded over centuries',
        description: 'Golden Fort - one of the few living forts in the world.',
        significance: 'Living fort, Silk Route trading center',
        visitingHours: 'Open 24 hours',
        entryFee: 'Free entry, ₹50 for palace',
        bestTime: 'October to March',
        nearbyAttractions: 'Patwon Ki Haveli, Sam Sand Dunes',
        icon: '🌄'
    },
    'chittorgarh fort': {
        name: 'Chittorgarh Fort',
        location: 'Chittorgarh, Rajasthan',
        state: 'Rajasthan',
        lat: 24.8829,
        lng: 74.6470,
        built: '7th Century',
        builtBy: 'Mauryan rulers',
        architecture: 'Rajput Architecture',
        unesco: 'Yes (2013)',
        constructionCost: 'Built over centuries',
        timePeriod: 'Over 800 years',
        description: 'Largest fort in India covering 700 acres.',
        significance: 'Symbol of Rajput pride and sacrifice',
        visitingHours: '9:45 AM - 5:45 PM',
        entryFee: '₹50 for Indians, ₹300 for Foreigners',
        bestTime: 'October to March',
        nearbyAttractions: 'Vijay Stambh, Kirti Stambh',
        icon: '🏔️'
    },
    
    // Maharashtra Forts
    'raigad fort': {
        name: 'Raigad Fort',
        location: 'Raigad, Maharashtra',
        state: 'Maharashtra',
        lat: 18.2356,
        lng: 73.4406,
        built: '1030 (renovated 1656)',
        builtBy: 'Chhatrapati Shivaji',
        architecture: 'Maratha Architecture',
        unesco: 'No',
        constructionCost: 'Maratha empire investment',
        timePeriod: 'Major renovation 10 years',
        description: 'Capital of Maratha Empire, coronation site of Shivaji Maharaj.',
        significance: 'Maratha capital, Shivaji coronation',
        visitingHours: '8:00 AM - 6:00 PM',
        entryFee: '₹30 for Indians',
        bestTime: 'October to February',
        nearbyAttractions: 'Raigad Ropeway, Takmak Tok',
        icon: '⚜️'
    },
    'sinhagad fort': {
        name: 'Sinhagad Fort',
        location: 'Pune, Maharashtra',
        state: 'Maharashtra',
        lat: 18.3664,
        lng: 73.7556,
        built: '2nd Century CE',
        builtBy: 'Ancient builders',
        architecture: 'Maratha Military',
        unesco: 'No',
        constructionCost: 'Fortified over centuries',
        timePeriod: '1800+ years',
        description: 'Lion Fort, famous for Battle of Sinhagad.',
        significance: 'Tanaji Malusare martyrdom site',
        visitingHours: 'Open 24 hours',
        entryFee: 'Free',
        bestTime: 'October to February',
        nearbyAttractions: 'Khadakwasla Dam, Pune',
        icon: '🦁'
    },
    
    // Add more forts...
    'golconda fort': {
        name: 'Golconda Fort',
        location: 'Hyderabad, Telangana',
        state: 'Telangana',
        lat: 17.3833,
        lng: 78.4011,
        built: '13th Century',
        builtBy: 'Kakatiya Dynasty',
        architecture: 'Indo-Islamic',
        unesco: 'No',
        constructionCost: '5 million gold coins',
        timePeriod: 'Expanded over 400 years',
        description: 'Famous for acoustic architecture and diamonds.',
        significance: 'Diamond trading center, Koh-i-Noor origin',
        visitingHours: '9:00 AM - 5:30 PM',
        entryFee: '₹25 for Indians, ₹300 for Foreigners',
        bestTime: 'October to March',
        nearbyAttractions: 'Qutb Shahi Tombs, Charminar',
        icon: '👑'
    },
    'agra fort': {
        name: 'Agra Fort',
        location: 'Agra, Uttar Pradesh',
        state: 'Uttar Pradesh',
        lat: 27.1795,
        lng: 78.0211,
        built: '1565-1573',
        builtBy: 'Emperor Akbar',
        architecture: 'Mughal Architecture',
        unesco: 'Yes (1983)',
        constructionCost: '3.5 million rupees',
        timePeriod: '8 years',
        description: 'Main residence of Mughal emperors until 1638.',
        significance: 'Shah Jahan imprisonment site',
        visitingHours: '6:00 AM - 6:00 PM',
        entryFee: '₹50 for Indians, ₹650 for Foreigners',
        bestTime: 'October to March',
        nearbyAttractions: 'Taj Mahal, Fatehpur Sikri',
        icon: '🏛️'
    },
    'bekal fort': {
        name: 'Bekal Fort',
        location: 'Kasaragod, Kerala',
        state: 'Kerala',
        lat: 12.3914,
        lng: 75.0355,
        built: '1650s',
        builtBy: 'Shivappa Nayaka',
        architecture: 'Coastal Defense Fort',
        unesco: 'No',
        constructionCost: 'Keladi Nayaka treasury',
        timePeriod: 'Several years',
        description: 'Largest fort in Kerala on Arabian Sea coast.',
        significance: 'Largest Kerala fort, film location',
        visitingHours: '8:00 AM - 5:30 PM',
        entryFee: '₹25 for Indians',
        bestTime: 'October to March',
        nearbyAttractions: 'Bekal Beach, Chandragiri Fort',
        icon: '🌊'
    }
};

// Information categories
const infoCategories = [
    { icon: '📜', title: 'Historical Background', desc: 'Detailed historical context including dynasties, construction era, battles, and historical role' },
    { icon: '🏗️', title: 'Architectural Details', desc: 'Comprehensive information about architectural styles, materials, unique features' },
    { icon: '👑', title: 'Rulers & Dynasties', desc: 'Learn about great emperors and warriors who commissioned these forts' },
    { icon: '⚔️', title: 'Battle Chronicles', desc: 'Discover epic sieges, legendary battles, and military strategies' },
    { icon: '🎨', title: 'Art & Culture', desc: 'Explore artistic treasures - carvings, mirror work, frescoes, paintings' },
    { icon: '🗺️', title: 'Location & Access', desc: 'Real-time GPS coordinates, interactive maps, directions from major cities' },
    { icon: '💰', title: 'Visit Planning', desc: 'Current entry fees, visiting hours, holidays, best time to visit' },
    { icon: '🏛️', title: 'UNESCO Heritage', desc: 'UNESCO World Heritage status, conservation efforts, restoration projects' },
    { icon: '📸', title: 'Photography & Tours', desc: 'Best photography spots, sunrise/sunset timings, guided tour availability' },
    { icon: '🍽️', title: 'Nearby Amenities', desc: 'Restaurants, hotels, parking facilities, restrooms, drinking water' },
    { icon: '🎭', title: 'Cultural Significance', desc: 'Role in literature, folklore, cinema, festivals, local legends' },
    { icon: '🔐', title: 'Security & Preservation', desc: 'ASI maintenance, security measures, visitor guidelines' },
    { icon: '🌟', title: 'Hidden Gems & Secrets', desc: 'Lesser-known chambers, secret passages, underground tunnels' },
    { icon: '📚', title: 'Educational Resources', desc: 'Study materials, research papers, archaeological findings' },
    { icon: '🎥', title: 'Multimedia Gallery', desc: '360° virtual tours, drone footage, historical paintings, videos' },
    { icon: '⏰', title: 'Timeline & Chronology', desc: 'Interactive timeline showing construction phases and historical events' },
    { icon: '🛡️', title: 'Defense Systems', desc: 'Fortification techniques, moats, bastions, military architecture' },
    { icon: '💎', title: 'Treasures & Artifacts', desc: 'Royal treasures, weaponry, jewelry, museum artifacts' },
    { icon: '🌍', title: 'Global Comparisons', desc: 'Compare with famous fortresses worldwide' },
    { icon: '🎓', title: 'Expert Commentary', desc: 'Insights from historians, archaeologists, architects' },
    { icon: '🌦️', title: 'Weather & Seasons', desc: 'Detailed weather throughout the year, temperature ranges' },
    { icon: '🚶', title: 'Visitor Experience', desc: 'Average time required, walking routes, accessibility' },
    { icon: '🏺', title: 'Archaeological Excavations', desc: 'Latest discoveries, ongoing excavation projects' },
    { icon: '🎪', title: 'Events & Festivals', desc: 'Sound & light shows, heritage walks, special celebrations' },
    { icon: '📱', title: 'Digital Experience', desc: 'AR/VR experiences, mobile apps, audio guides' },
    { icon: '🌱', title: 'Eco-Tourism Initiatives', desc: 'Sustainable tourism practices, environmental conservation' },
    { icon: '👨‍👩‍👧‍👦', title: 'Family-Friendly Features', desc: 'Child-friendly areas, educational programs for kids' },
    { icon: '🎬', title: 'Cinema & Media', desc: 'Bollywood and Hollywood movies filmed at the fort' },
    { icon: '🛍️', title: 'Souvenir & Shopping', desc: 'Gift shops, local handicrafts, traditional artifacts' },
    { icon: '🍴', title: 'Local Cuisine', desc: 'Traditional dishes, famous restaurants, culinary heritage' }
];